import { Charity, QuizQuestion, Donation } from '../types'

// Somnia Testnet Configuration (Placeholder - user needs to configure their own RPC)
export const SOMNIA_TESTNET_CONFIG = {
  chainId: '0xc488', // Example Somnia Testnet Chain ID (replace with actual if different)
  chainName: 'Somnia Testnet',
  nativeCurrency: {
    name: 'STT',
    symbol: 'STT',
    decimals: 18,
  },
  rpcUrls: ['https://vsf-rpc.somnia.network/'], // Replace with actual Somnia Testnet RPC URL
  blockExplorerUrls: ['https://explorer.somnia.network'], // Replace with actual Somnia Testnet Explorer URL
}

// Placeholder Smart Contract ABI and Address
// IMPORTANT: User needs to deploy their own contract to Somnia Testnet and update these values.
export const CONTRACT_ADDRESS = '0x841b8199E6d3Db3C6f264f6C2bd8848b3cA64223' // Example address
export const CONTRACT_ABI = [
  {
    "inputs": [],
    "stateMutability": "nonpayable",
    "type": "constructor"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "address",
        "name": "donor",
        "type": "address"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "charityAddress",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "amount",
        "type": "uint256"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "timestamp",
        "type": "uint256"
      }
    ],
    "name": "DonationMade",
    "type": "event"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "_charityAddress",
        "type": "address"
      }
    ],
    "name": "donate",
    "outputs": [],
    "stateMutability": "payable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "name": "donations",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "owner",
    "outputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
]


export const QUIZ_QUESTIONS: QuizQuestion[] = [
  {
    id: 'category',
    question: 'Which cause resonates most with you?',
    type: 'select',
    options: [
      { label: 'Environmental Protection', value: 'Environment' },
      { label: 'Healthcare & Medical Research', value: 'Health' },
      { label: 'Education & Youth Development', value: 'Education' },
      { label: 'Poverty & Hunger Relief', value: 'Poverty' },
      { label: 'Animal Welfare', value: 'Animals' },
      { label: 'Arts & Culture', value: 'Arts' },
    ],
  },
  {
    id: 'budget',
    question: 'What is your typical donation budget?',
    type: 'select',
    options: [
      { label: 'Under $50', value: 'low' },
      { label: '$50 - $200', value: 'medium' },
      { label: '$200 - $500', value: 'high' },
      { label: 'Over $500', value: 'very_high' },
    ],
  },
  {
    id: 'impact',
    question: 'How do you prefer to see your donation\'s impact?',
    type: 'select',
    options: [
      { label: 'Direct, tangible results (e.g., meals provided)', value: 'direct' },
      { label: 'Long-term systemic change (e.g., policy advocacy)', value: 'systemic' },
      { label: 'Research & innovation', value: 'research' },
      { label: 'Community building & support', value: 'community' },
    ],
  },
  {
    id: 'geography',
    question: 'Where would you like your donation to make a difference?',
    type: 'select',
    options: [
      { label: 'Local (within my city/region)', value: 'local' },
      { label: 'National (within my country)', value: 'national' },
      { label: 'International (global reach)', value: 'international' },
    ],
  },
  {
    id: 'transparency',
    question: 'How important is financial transparency to you?',
    type: 'select',
    options: [
      { label: 'Extremely important (detailed reports)', value: 'high' },
      { label: 'Moderately important (clear overview)', value: 'medium' },
      { label: 'Less important (trust the organization)', value: 'low' },
    ],
  },
  {
    id: 'size',
    question: 'Do you prefer supporting large, established charities or smaller, emerging ones?',
    type: 'select',
    options: [
      { label: 'Large & established', value: 'large' },
      { label: 'Small & emerging', value: 'small' },
      { label: 'No preference', value: 'any' },
    ],
  },
]

export const CHARITIES: Charity[] = [
  {
    id: '1',
    name: 'Green Earth Alliance',
    category: 'Environment',
    description: 'Dedicated to protecting natural habitats and promoting sustainable living through reforestation and conservation efforts.',
    impact: 'direct',
    geography: 'international',
    transparency: 'high',
    size: 'large',
    verified: true,
    imageUrl: 'https://images.pexels.com/photos/1108701/pexels-photo-1108701.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    targetAmount: 100000,
    raisedAmount: 75000,
    address: '0x1234567890123456789012345678901234567891',
    about: 'Green Earth Alliance is a global non-profit organization committed to combating climate change and preserving biodiversity. We work with local communities to implement sustainable practices and advocate for environmental policies.',
    financials: 'Our annual reports are publicly available, detailing every expenditure and source of funding. We maintain a 90% program efficiency ratio.',
    updates: [
      { date: '2024-07-20', text: 'Successfully planted 10,000 trees in the Amazon rainforest.' },
      { date: '2024-06-15', text: 'Launched new initiative to protect endangered marine species.' },
    ],
  },
  {
    id: '2',
    name: 'Hope for Health Foundation',
    category: 'Health',
    description: 'Funding cutting-edge medical research and providing access to healthcare for underserved communities worldwide.',
    impact: 'research',
    geography: 'international',
    transparency: 'medium',
    size: 'large',
    verified: true,
    imageUrl: 'https://images.pexels.com/photos/4033148/pexels-photo-4033148.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    targetAmount: 250000,
    raisedAmount: 180000,
    address: '0x1234567890123456789012345678901234567892',
    about: 'Hope for Health Foundation is at the forefront of medical innovation, supporting research into cures for chronic diseases and ensuring that life-saving treatments reach those who need them most, regardless of their economic status.',
    financials: 'We provide quarterly financial summaries and an annual audit. Our administrative costs are kept below 15% to maximize impact.',
    updates: [
      { date: '2024-07-18', text: 'Breakthrough in cancer research announced by our funded scientists.' },
      { date: '2024-06-01', text: 'Opened new mobile clinic in rural Africa, serving 500+ patients.' },
    ],
  },
  {
    id: '3',
    name: 'Future Scholars Initiative',
    category: 'Education',
    description: 'Empowering youth through scholarships, mentorship programs, and access to quality educational resources in underprivileged areas.',
    impact: 'systemic',
    geography: 'national',
    transparency: 'high',
    size: 'medium',
    verified: true,
    imageUrl: 'https://images.pexels.com/photos/3019267/pexels-photo-3019267.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    targetAmount: 80000,
    raisedAmount: 60000,
    address: '0x1234567890123456789012345678901234567893',
    about: 'Future Scholars Initiative believes that education is the key to breaking cycles of poverty. We provide comprehensive support to students from kindergarten through college, ensuring they have the tools and guidance to succeed.',
    financials: 'Detailed financial reports are available on our website. We pride ourselves on efficient use of funds, with 88% directly supporting educational programs.',
    updates: [
      { date: '2024-07-22', text: 'Graduation ceremony for 150 scholarship recipients.' },
      { date: '2024-05-20', text: 'Launched new STEM education program for middle schoolers.' },
    ],
  },
  {
    id: '4',
    name: 'Global Hunger Relief',
    category: 'Poverty',
    description: 'Providing emergency food aid and sustainable agricultural solutions to communities facing severe food insecurity.',
    impact: 'direct',
    geography: 'international',
    transparency: 'high',
    size: 'large',
    verified: true,
    imageUrl: 'https://images.pexels.com/photos/699520/pexels-photo-699520.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    targetAmount: 300000,
    raisedAmount: 280000,
    address: '0x1234567890123456789012345678901234567894',
    about: 'Global Hunger Relief is a leading organization in the fight against hunger. We deliver immediate food assistance during crises and implement long-term projects to empower communities to achieve food self-sufficiency.',
    financials: 'Our financial statements are audited annually and available online. We ensure that over 95% of donations go directly to program services.',
    updates: [
      { date: '2024-07-10', text: 'Delivered 1 million meals to drought-affected regions.' },
      { date: '2024-06-25', text: 'Established new community farm in rural India.' },
    ],
  },
  {
    id: '5',
    name: 'Paws & Claws Sanctuary',
    category: 'Animals',
    description: 'Rescuing, rehabilitating, and rehoming abandoned and abused animals, advocating for animal rights.',
    impact: 'direct',
    geography: 'local',
    transparency: 'medium',
    size: 'small',
    verified: false,
    imageUrl: 'https://images.pexels.com/photos/160846/french-bulldog-paw-animal-dog-160846.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    targetAmount: 30000,
    raisedAmount: 22000,
    address: '0x1234567890123456789012345678901234567895',
    about: 'Paws & Claws Sanctuary provides a safe haven for animals in need. We offer medical care, behavioral training, and loving foster homes, working tirelessly to find forever families for every animal.',
    financials: 'We publish an annual report summarizing our income and expenses. As a smaller organization, we rely heavily on volunteer support.',
    updates: [
      { date: '2024-07-15', text: 'Successfully rehomed 15 cats and dogs this month.' },
      { date: '2024-06-10', text: 'Hosted a successful adoption drive, finding homes for 8 animals.' },
    ],
  },
  {
    id: '6',
    name: 'Cultural Heritage Preservation',
    category: 'Arts',
    description: 'Protecting and promoting historical sites, traditional arts, and cultural practices for future generations.',
    impact: 'systemic',
    geography: 'national',
    transparency: 'high',
    size: 'medium',
    verified: true,
    imageUrl: 'https://images.pexels.com/photos/161702/pexels-photo-161702.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    targetAmount: 150000,
    raisedAmount: 110000,
    address: '0x1234567890123456789012345678901234567896',
    about: 'Cultural Heritage Preservation works to safeguard the rich tapestry of human history and creativity. We restore ancient monuments, support traditional artisans, and educate the public on the importance of cultural diversity.',
    financials: 'Our financial records are fully transparent and available for public review. We partner with government agencies and private donors.',
    updates: [
      { date: '2024-07-05', text: 'Completed restoration of the historic Grand Theater.' },
      { date: '2024-05-30', text: 'Launched digital archive of indigenous oral histories.' },
    ],
  },
  {
    id: '7',
    name: 'Ocean Guardians',
    category: 'Environment',
    description: 'Working to clean up plastic pollution in oceans and protect marine ecosystems from overfishing and habitat destruction.',
    impact: 'direct',
    geography: 'international',
    transparency: 'high',
    size: 'large',
    verified: true,
    imageUrl: 'https://images.pexels.com/photos/1000445/pexels-photo-1000445.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    targetAmount: 180000,
    raisedAmount: 150000,
    address: '0x1234567890123456789012345678901234567897',
    about: 'Ocean Guardians is a leading voice for marine conservation. We conduct large-scale ocean cleanups, advocate for stronger environmental regulations, and educate the public on the importance of healthy oceans.',
    financials: 'Annual audited reports are available. 92% of funds directly support our ocean cleanup and conservation programs.',
    updates: [
      { date: '2024-07-25', text: 'Removed 5 tons of plastic from the Pacific Ocean.' },
      { date: '2024-06-18', text: 'Successfully lobbied for new fishing quotas in protected areas.' },
    ],
  },
  {
    id: '8',
    name: 'Mental Wellness Advocates',
    category: 'Health',
    description: 'Providing free mental health support, counseling, and awareness campaigns to reduce stigma.',
    impact: 'community',
    geography: 'local',
    transparency: 'medium',
    size: 'small',
    verified: false,
    imageUrl: 'https://images.pexels.com/photos/4145353/pexels-photo-4145353.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    targetAmount: 40000,
    raisedAmount: 30000,
    address: '0x1234567890123456789012345678901234567898',
    about: 'Mental Wellness Advocates offers accessible mental health resources to everyone. We believe that mental health is as important as physical health and strive to create a supportive community where individuals can thrive.',
    financials: 'Our financial statements are available upon request. We are a grassroots organization with a strong volunteer base.',
    updates: [
      { date: '2024-07-12', text: 'Hosted a free community mental health workshop.' },
      { date: '2024-06-05', text: 'Expanded our online peer support network.' },
    ],
  },
  {
    id: '9',
    name: 'Code for Tomorrow',
    category: 'Education',
    description: 'Offering free coding bootcamps and tech education to underprivileged youth, preparing them for future careers.',
    impact: 'systemic',
    geography: 'national',
    transparency: 'high',
    size: 'medium',
    verified: true,
    imageUrl: 'https://images.pexels.com/photos/3861969/pexels-photo-3861969.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    targetAmount: 90000,
    raisedAmount: 70000,
    address: '0x1234567890123456789012345678901234567899',
    about: 'Code for Tomorrow bridges the digital divide by providing high-quality tech education to youth from low-income backgrounds. We equip them with in-demand skills for the rapidly evolving tech industry.',
    financials: 'Transparent financial reporting is a core value. Our annual reports detail program costs and impact metrics.',
    updates: [
      { date: '2024-07-20', text: 'Graduated 50 students from our advanced web development bootcamp.' },
      { date: '2024-06-15', text: 'Partnered with local tech companies for internship opportunities.' },
    ],
  },
  {
    id: '10',
    name: 'Shelter for All',
    category: 'Poverty',
    description: 'Providing safe housing, food, and support services for homeless individuals and families.',
    impact: 'direct',
    geography: 'local',
    transparency: 'medium',
    size: 'medium',
    verified: true,
    imageUrl: 'https://images.pexels.com/photos/2724749/pexels-photo-2724749.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    targetAmount: 120000,
    raisedAmount: 95000,
    address: '0x12345678901234567890123456789012345678A0',
    about: 'Shelter for All offers comprehensive support to those experiencing homelessness. Beyond providing immediate needs like shelter and food, we connect individuals with resources for employment, healthcare, and long-term housing.',
    financials: 'We publish an annual financial overview. Our focus is on maximizing direct aid to those in need.',
    updates: [
      { date: '2024-07-18', text: 'Opened a new temporary shelter facility, increasing capacity by 30%.' },
      { date: '2024-06-01', text: 'Helped 20 families transition into permanent housing.' },
    ],
  },
  {
    id: '11',
    name: 'Wildlife Protectors',
    category: 'Animals',
    description: 'Protecting endangered species and their habitats through anti-poaching efforts and wildlife rehabilitation.',
    impact: 'direct',
    geography: 'international',
    transparency: 'high',
    size: 'large',
    verified: true,
    imageUrl: 'https://images.pexels.com/photos/145939/pexels-photo-145939.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    targetAmount: 200000,
    raisedAmount: 160000,
    address: '0x12345678901234567890123456789012345678A1',
    about: 'Wildlife Protectors is dedicated to safeguarding the planet\'s most vulnerable species. Our teams work on the ground in critical habitats, combating illegal wildlife trade and providing care for injured animals.',
    financials: 'Our financial reports are fully transparent and audited annually. We ensure a high percentage of funds go directly to field operations.',
    updates: [
      { date: '2024-07-10', text: 'Rescued a rare snow leopard cub from poachers.' },
      { date: '2024-06-25', text: 'Expanded protected area for rhinos in Africa.' },
    ],
  },
  {
    id: '12',
    name: 'Art for Community',
    category: 'Arts',
    description: 'Bringing art education and creative expression opportunities to underserved communities.',
    impact: 'community',
    geography: 'local',
    transparency: 'low',
    size: 'small',
    verified: false,
    imageUrl: 'https://images.pexels.com/photos/102127/pexels-photo-102127.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    targetAmount: 25000,
    raisedAmount: 18000,
    address: '0x12345678901234567890123456789012345678A2',
    about: 'Art for Community believes in the transformative power of art. We offer free art classes, workshops, and public art projects, fostering creativity and community engagement in neighborhoods that lack access to arts programs.',
    financials: 'As a small, volunteer-run organization, our financial details are available upon request. We prioritize direct program funding.',
    updates: [
      { date: '2024-07-05', text: 'Completed a new mural project in the city center.' },
      { date: '2024-05-30', text: 'Hosted a successful youth art exhibition.' },
    ],
  },
  {
    id: '13',
    name: 'Clean Water Initiative',
    category: 'Environment',
    description: 'Providing access to clean and safe drinking water in developing countries through well construction and water purification projects.',
    impact: 'direct',
    geography: 'international',
    transparency: 'high',
    size: 'large',
    verified: true,
    imageUrl: 'https://images.pexels.com/photos/1000445/pexels-photo-1000445.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    targetAmount: 150000,
    raisedAmount: 120000,
    address: '0x12345678901234567890123456789012345678A3',
    about: 'The Clean Water Initiative is dedicated to solving the global water crisis. We implement sustainable water solutions, including drilling wells, installing filtration systems, and educating communities on hygiene practices.',
    financials: 'Our financial reports are audited annually and publicly accessible. We ensure maximum impact with minimal overhead.',
    updates: [
      { date: '2024-07-28', text: 'Completed 10 new well installations in rural villages.' },
      { date: '2024-06-20', text: 'Launched a new water purification project in Southeast Asia.' },
    ],
  },
  {
    id: '14',
    name: 'Children\'s Medical Fund',
    category: 'Health',
    description: 'Supporting children with critical illnesses by covering medical expenses and providing emotional support to families.',
    impact: 'direct',
    geography: 'national',
    transparency: 'high',
    size: 'medium',
    verified: true,
    imageUrl: 'https://images.pexels.com/photos/3985163/pexels-photo-3985163.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    targetAmount: 180000,
    raisedAmount: 140000,
    address: '0x12345678901234567890123456789012345678A4',
    about: 'The Children\'s Medical Fund provides a lifeline to families facing the immense challenges of childhood illness. We cover treatment costs, offer family support programs, and advocate for better pediatric care.',
    financials: 'We maintain high transparency with detailed financial reports available on our website. Over 90% of donations directly assist children.',
    updates: [
      { date: '2024-07-15', text: 'Funded life-saving surgery for 5 children this month.' },
      { date: '2024-06-10', text: 'Hosted a support group for parents of children with chronic conditions.' },
    ],
  },
  {
    id: '15',
    name: 'Literacy for All',
    category: 'Education',
    description: 'Promoting literacy through book donations, reading programs, and adult education classes.',
    impact: 'systemic',
    geography: 'local',
    transparency: 'medium',
    size: 'small',
    verified: false,
    imageUrl: 'https://images.pexels.com/photos/261909/pexels-photo-261909.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    targetAmount: 35000,
    raisedAmount: 28000,
    address: '0x12345678901234567890123456789012345678A5',
    about: 'Literacy for All believes that reading is a fundamental right. We work to improve literacy rates in our community by providing free books, running engaging reading programs for children, and offering adult literacy classes.',
    financials: 'Our financial summaries are available to donors. We are a community-driven organization with a strong volunteer base.',
    updates: [
      { date: '2024-07-22', text: 'Distributed 1,000 books to local schools and libraries.' },
      { date: '2024-06-05', text: 'Launched a new after-school reading club.' },
    ],
  },
  {
    id: '16',
    name: 'Microfinance for Empowerment',
    category: 'Poverty',
    description: 'Providing small loans and business training to women in developing countries to foster economic independence.',
    impact: 'systemic',
    geography: 'international',
    transparency: 'high',
    size: 'medium',
    verified: true,
    imageUrl: 'https://images.pexels.com/photos/3760067/pexels-photo-3760067.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    targetAmount: 100000,
    raisedAmount: 85000,
    address: '0x12345678901234567890123456789012345678A6',
    about: 'Microfinance for Empowerment empowers women entrepreneurs in underserved regions. By providing access to capital and business education, we help them build sustainable livelihoods and uplift their families and communities.',
    financials: 'Detailed financial reports and impact assessments are published annually. We track loan repayment rates and business growth.',
    updates: [
      { date: '2024-07-10', text: 'Provided microloans to 50 new women entrepreneurs.' },
      { date: '2024-06-25', text: 'Hosted a business skills training workshop for beneficiaries.' },
    ],
  },
  {
    id: '17',
    name: 'Save Our Reefs',
    category: 'Environment',
    description: 'Dedicated to coral reef restoration and protection, combating ocean acidification and pollution.',
    impact: 'direct',
    geography: 'international',
    transparency: 'high',
    size: 'large',
    verified: true,
    imageUrl: 'https://images.pexels.com/photos/1000445/pexels-photo-1000445.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    targetAmount: 170000,
    raisedAmount: 130000,
    address: '0x12345678901234567890123456789012345678A7',
    about: 'Save Our Reefs is at the forefront of coral reef conservation. We implement innovative restoration techniques, conduct scientific research, and advocate for policies to protect these vital marine ecosystems.',
    financials: 'Annual audited reports are available, demonstrating our commitment to financial transparency and effective program spending.',
    updates: [
      { date: '2024-07-20', text: 'Successfully transplanted 5,000 coral fragments onto degraded reefs.' },
      { date: '2024-06-15', text: 'Published new research on the impact of microplastics on coral health.' },
    ],
  },
  {
    id: '18',
    name: 'Elderly Care Network',
    category: 'Health',
    description: 'Providing companionship, meal delivery, and medical assistance to elderly individuals living alone.',
    impact: 'community',
    geography: 'local',
    transparency: 'medium',
    size: 'small',
    verified: false,
    imageUrl: 'https://images.pexels.com/photos/3823204/pexels-photo-3823204.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    targetAmount: 45000,
    raisedAmount: 35000,
    address: '0x12345678901234567890123456789012345678A8',
    about: 'The Elderly Care Network ensures that seniors in our community live with dignity and support. We offer a range of services, from daily check-ins and meal delivery to transportation for medical appointments, combating isolation and promoting well-being.',
    financials: 'Our financial summaries are available to our donors and community partners. We prioritize direct services to seniors.',
    updates: [
      { date: '2024-07-18', text: 'Expanded our meal delivery service to cover new neighborhoods.' },
      { date: '2024-06-01', text: 'Hosted a successful intergenerational social event.' },
    ],
  },
  {
    id: '19',
    name: 'Global Arts Exchange',
    category: 'Arts',
    description: 'Promoting cross-cultural understanding through international art exhibitions and artist exchange programs.',
    impact: 'systemic',
    geography: 'international',
    transparency: 'high',
    size: 'large',
    verified: true,
    imageUrl: 'https://images.pexels.com/photos/161702/pexels-photo-161702.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    targetAmount: 160000,
    raisedAmount: 120000,
    address: '0x12345678901234567890123456789012345678A9',
    about: 'Global Arts Exchange fosters dialogue and understanding between cultures through the universal language of art. We organize international exhibitions, facilitate artist residencies, and promote cultural education worldwide.',
    financials: 'Our financial reports are audited annually and publicly available, reflecting our commitment to transparency and global impact.',
    updates: [
      { date: '2024-07-25', text: 'Opened a new exhibition featuring contemporary African artists.' },
      { date: '2024-06-18', text: 'Launched a virtual artist-in-residence program connecting artists globally.' },
    ],
  },
  {
    id: '20',
    name: 'Youth Sports League',
    category: 'Education', // Can also be considered community/health
    description: 'Providing organized sports activities and mentorship for underprivileged youth, promoting teamwork and healthy lifestyles.',
    impact: 'community',
    geography: 'local',
    transparency: 'medium',
    size: 'small',
    verified: false,
    imageUrl: 'https://images.pexels.com/photos/1086178/pexels-photo-1086178.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    targetAmount: 50000,
    raisedAmount: 38000,
    address: '0x12345678901234567890123456789012345678B0',
    about: 'The Youth Sports League offers a safe and supportive environment for children to engage in sports, learn valuable life skills, and build confidence. We believe in the power of play to foster personal growth and community spirit.',
    financials: 'We provide annual financial summaries to our community and donors. Our operations are heavily supported by volunteers.',
    updates: [
      { date: '2024-07-12', text: 'Successfully completed our summer soccer league with over 200 participants.' },
      { date: '2024-06-05', text: 'Hosted a free sports clinic for aspiring young athletes.' },
    ],
  },
  {
    id: '21',
    name: 'Disaster Relief Aid',
    category: 'Poverty',
    description: 'Providing immediate humanitarian assistance to communities affected by natural disasters and conflicts.',
    impact: 'direct',
    geography: 'international',
    transparency: 'high',
    size: 'large',
    verified: true,
    imageUrl: 'https://images.pexels.com/photos/325521/pexels-photo-325521.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    targetAmount: 500000,
    raisedAmount: 450000,
    address: '0x12345678901234567890123456789012345678B1',
    about: 'Disaster Relief Aid is a rapid-response organization delivering critical assistance during emergencies. We provide food, shelter, medical care, and psychological support to those impacted by disasters worldwide.',
    financials: 'Our financial operations are rigorously audited, and reports are publicly available. We prioritize speed and efficiency in aid delivery.',
    updates: [
      { date: '2024-07-01', text: 'Deployed emergency teams to flood-affected regions in Asia.' },
      { date: '2024-05-15', text: 'Provided medical supplies to conflict zones.' },
    ],
  },
  {
    id: '22',
    name: 'Animal Rescue League',
    category: 'Animals',
    description: 'Rescuing and rehabilitating injured wildlife and advocating for stronger animal protection laws.',
    impact: 'direct',
    geography: 'national',
    transparency: 'medium',
    size: 'medium',
    verified: true,
    imageUrl: 'https://images.pexels.com/photos/160846/french-bulldog-paw-animal-dog-160846.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    targetAmount: 70000,
    raisedAmount: 55000,
    address: '0x12345678901234567890123456789012345678B2',
    about: 'The Animal Rescue League is dedicated to the welfare of all animals. We operate a state-of-the-art wildlife hospital, conduct rescue missions, and work with lawmakers to improve animal rights legislation.',
    financials: 'Annual financial reports are available, detailing our program expenses and fundraising efforts. We are committed to responsible stewardship of donations.',
    updates: [
      { date: '2024-07-15', text: 'Successfully rehabilitated and released 10 eagles back into the wild.' },
      { date: '2024-06-10', text: 'Lobbied for a new bill to protect endangered marine mammals.' },
    ],
  },
  {
    id: '23',
    name: 'Community Arts Center',
    category: 'Arts',
    description: 'Offering affordable art classes, workshops, and gallery space to local artists and residents.',
    impact: 'community',
    geography: 'local',
    transparency: 'medium',
    size: 'small',
    verified: false,
    imageUrl: 'https://images.pexels.com/photos/102127/pexels-photo-102127.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    targetAmount: 40000,
    raisedAmount: 30000,
    address: '0x12345678901234567890123456789012345678B3',
    about: 'The Community Arts Center is a vibrant hub for creativity and cultural exchange. We provide accessible art education for all ages, showcase local talent, and host events that enrich our community\'s artistic landscape.',
    financials: 'Our financial statements are available to our members and supporters. We rely on grants, donations, and class fees.',
    updates: [
      { date: '2024-07-08', text: 'Opened a new exhibition featuring emerging local painters.' },
      { date: '2024-06-01', text: 'Launched a summer art camp for children and teens.' },
    ],
  },
  {
    id: '24',
    name: 'Sustainable Agriculture Fund',
    category: 'Environment',
    description: 'Promoting organic farming practices and supporting farmers in transitioning to sustainable agriculture.',
    impact: 'systemic',
    geography: 'national',
    transparency: 'high',
    size: 'medium',
    verified: true,
    imageUrl: 'https://images.pexels.com/photos/1108701/pexels-photo-1108701.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    targetAmount: 90000,
    raisedAmount: 70000,
    address: '0x12345678901234567890123456789012345678B4',
    about: 'The Sustainable Agriculture Fund works to create a healthier planet and more resilient food systems. We provide training, resources, and financial support to farmers adopting environmentally friendly practices.',
    financials: 'Detailed financial reports are published annually, highlighting our investments in sustainable farming initiatives and their impact.',
    updates: [
      { date: '2024-07-20', text: 'Supported 20 farms in transitioning to certified organic production.' },
      { date: '2024-06-15', text: 'Hosted a national conference on regenerative agriculture.' },
    ],
  },
  {
    id: '25',
    name: 'Global Health Corps',
    category: 'Health',
    description: 'Deploying medical professionals to crisis zones and underserved regions to provide essential healthcare services.',
    impact: 'direct',
    geography: 'international',
    transparency: 'high',
    size: 'large',
    verified: true,
    imageUrl: 'https://images.pexels.com/photos/4033148/pexels-photo-4033148.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    targetAmount: 220000,
    raisedAmount: 190000,
    address: '0x12345678901234567890123456789012345678B5',
    about: 'Global Health Corps is a frontline organization delivering critical medical aid where it\'s needed most. Our teams of doctors, nurses, and public health experts work in challenging environments to save lives and improve health outcomes.',
    financials: 'Our financial statements are audited annually and publicly available, demonstrating our commitment to efficient and impactful aid.',
    updates: [
      { date: '2024-07-10', text: 'Deployed a surgical team to a conflict-affected region.' },
      { date: '2024-06-25', text: 'Provided vaccinations for 10,000 children in a remote village.' },
    ],
  },
  {
    id: '26',
    name: 'Youth Empowerment Network',
    category: 'Education',
    description: 'Mentorship programs, leadership training, and skill-building workshops for at-risk youth.',
    impact: 'systemic',
    geography: 'local',
    transparency: 'medium',
    size: 'small',
    verified: false,
    imageUrl: 'https://images.pexels.com/photos/3019267/pexels-photo-3019267.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    targetAmount: 60000,
    raisedAmount: 45000,
    address: '0x12345678901234567890123456789012345678B6',
    about: 'The Youth Empowerment Network is dedicated to nurturing the potential of every young person. We offer personalized mentorship, leadership development programs, and practical skill-building workshops to help youth achieve their goals.',
    financials: 'We provide annual financial summaries to our community. Our programs are largely supported by local grants and individual donations.',
    updates: [
      { date: '2024-07-15', text: 'Launched a new entrepreneurship program for high school students.' },
      { date: '2024-06-10', text: 'Mentored 30 youth through our summer leadership academy.' },
    ],
  },
]

export const INITIAL_DONATIONS: Donation[] = [
  {
    id: 'd1',
    charityId: '1',
    charityName: 'Green Earth Alliance',
    donorAddress: '0xDonor1AddressHere',
    amount: 0.5,
    timestamp: Date.now() - 86400000 * 5, // 5 days ago
    txHash: '0xabc123def456abc123def456abc123def456abc123def456abc123def456abc123',
  },
  {
    id: 'd2',
    charityId: '3',
    charityName: 'Future Scholars Initiative',
    donorAddress: '0xDonor2AddressHere',
    amount: 0.2,
    timestamp: Date.now() - 86400000 * 2, // 2 days ago
    txHash: '0xdef456abc123def456abc123def456abc123def456abc123def456abc123def456',
  },
  {
    id: 'd3',
    charityId: '1',
    charityName: 'Green Earth Alliance',
    donorAddress: '0xDonor1AddressHere',
    amount: 1.0,
    timestamp: Date.now() - 86400000 * 1, // 1 day ago
    txHash: '0x123def456abc123def456abc123def456abc123def456abc123def456abc123def',
  },
]
